[pytest]
addopts =
    --host=localhost
    --port=3307
    --database=prestashop
    --user=root
    --password=admin
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*